### ISSUE TITLE
Outputchache não é escalável

### ISSUE THREAD

**Issue by luizcarlosfaria** [andr3marra/rinha-de-backend-2023-q3-csharp#2]
https://github.com/andr3marra/rinha-de-backend-2023-q3-csharp/blob/b68d4ce8a6457380eafa9e7139f041a5a97fe998/src/Program.cs#L32

No momento que o exercício pediu 2 instâncias:

- propriedades estáticas 
- outputcache 
- response caching

passam a ser considerados agressores para a arquitetura e principalmente para o negócio.

**Comment by andr3marra** [comment]
Olá! Não tive a mesma compreensão que você, a proposta não especificava como as respostas deveriam ser geradas. Usamos strings estáticas para pular a serialização dessas respostas já conhecidas e que nunca variam. O Outputcache foi utlizado porque a  API era apenas criação e consulta, ou seja, após a primeira consulta bem sucedida todas as respostas podem ser retornadas iguais, sempre representando o estado que está persistido no banco, pois nunca serão atualizadas ou deletadas. Concordo que o uso indiscriminado do outputcache retornaria dados incoerentes, mas fizemos a configuração correta(espero) para melhorar a performance e continuar com respostas válidas.

**Comment by luizcarlosfaria** [comment]
Meu ponto é que o que para o exercício são solicitadas 2 instâncias. 
E assim o output cache de cada uma é diferente, com a evolução do estado do banco.

mudanças no estado não afetam o cache, por se tratar de mais de 1 instancia.

então abordagens como memory cache e outputcache ou qualquer coisa que não estaja fora da instância, e possa ser sensibilizado por outras instâncias, tem o potencial para gerar inconsistência.

Se temos um cache em memória ou outputcache  de 5 segundo, tudo que for realizado nesse período pela outra instância, não será exibido por nosso cache. Também a outra instância não terá a chance de atualizar ou limpar esse cache dessa instância aqui. 

Esse é o ponto central.

Grande abraço!

**Comment by akliemke** [comment]
Se houveram updates ou deletes nos dados, o que não é o caso aqui. 

Obrigado pelo feedback!
